import { colors } from './theme';

export const gameInstructions = {
  ko: {
    title: '플레이 방법',
    items: {
      tutorial: [
        '- 방향 버튼(▲▼◀▶)을 누르세요',
        '- 벽에 부딪힐 때까지 미끄러집니다',
        '- 오렌지색 칸에 "멈춰야" 승리합니다',
        '- 제한 시간 없이 편하게 연습하세요',
        '- 설정에서 이동 횟수 제한을 켤 수 있습니다',
        '- Undo로 최대 5번 되돌릴 수 있습니다',
        '- 패배 시 Try Again 또는 Reset으로 다시 시도하세요',
        '- Reset을 길게 누르면 게임이 처음부터 다시 시작됩니다',
        '- 10레벨을 클리어하면 챌린지 라운드가 열립니다',
      ],
      challenge: [
        '- 방향 버튼(▲▼◀▶)을 누르세요',
        '- 벽에 부딪힐 때까지 미끄러집니다',
        '- 오렌지색 칸에 "멈춰야" 승리합니다',
        '- 제한 시간이 끝나면 패배합니다',
        '- 이동 횟수 제한이 적용됩니다',
        '- Undo 없음 — 신중하게 이동하세요',
        '- 패배 시 Try Again 또는 Reset으로 다시 시도하세요',
        '- Reset을 길게 누르면 라운드 1부터 다시 시작됩니다',
        '- 50레벨을 클리어하면 라운드를 완료합니다',
      ],
    },
    legendTitle: '타일 설명',
    legend: [
      { color: colors.cellStart, label: '시작 (플레이어)' },
      { color: colors.cellGoal, label: '목표 — 여기서 멈춰야 합니다' },
      { color: colors.cellWall, label: '벽 — 통과 불가' },
      { color: colors.cellTrail, label: '이동 경로' },
      { color: colors.cellIce, label: '얼음 — 특수 타일 (곧 활성화)' },
    ],
    soundOn: '켜짐',
    soundOff: '꺼짐',
    soundLabel: '효과음',
    moveLimitOn: '켜짐',
    moveLimitOff: '꺼짐',
    moveLimitLabel: '이동 횟수 제한',
  },
  en: {
    title: 'How to play',
    items: {
      tutorial: [
        '- Press the arrow buttons (▲▼◀▶)',
        '- You slide until you hit a wall',
        '- You win only if you STOP on the orange tile',
        '- No time limit — learn at your own pace',
        '- Optional: enable move limit in settings below',
        '- Undo up to 5 times per level',
        '- On loss, tap Try Again or Reset to retry',
        '- Long-press Reset to restart the whole game',
        '- Beat Level 10 to unlock the Challenge Round',
      ],
      challenge: [
        '- Press the arrow buttons (▲▼◀▶)',
        '- You slide until you hit a wall',
        '- You win only if you STOP on the orange tile',
        '- Running out of time ends the level',
        '- Move limit is enforced each level',
        '- No undo — plan your moves carefully',
        '- On loss, tap Try Again or Reset to retry',
        '- Long-press Reset to restart from Round 1',
        '- Beat Level 50 to complete the round',
      ],
    },
    legendTitle: 'Tile legend',
    legend: [
      { color: colors.cellStart, label: 'Start (player)' },
      { color: colors.cellGoal, label: 'Goal — stop here to win' },
      { color: colors.cellWall, label: 'Wall — blocks movement' },
      { color: colors.cellTrail, label: 'Trail — path you traveled' },
      { color: colors.cellIce, label: 'Ice — special tile (mechanic coming)' },
    ],
    soundOn: 'On',
    soundOff: 'Off',
    soundLabel: 'Sound effects',
    moveLimitOn: 'On',
    moveLimitOff: 'Off',
    moveLimitLabel: 'Move limit',
  },
};
