import { StyleSheet } from 'react-native';

export const colors = {
  background: '#0B1220',
  surface: '#111A2E',
  surfaceBorder: '#1E2A45',
  buttonBg: '#1E2A45',
  buttonBorder: '#2B3B63',
  buttonPressed: '#263454',
  textPrimary: '#E6EEF9',
  textSecondary: '#B6C5E3',
  textMuted: '#93A4C7',
  accent: '#2563EB',
  accentText: '#FFFFFF',
  cellEmpty: '#0F172A',
  cellEmptyBorder: '#1B2844',
  cellWall: '#4B2E83',
  cellIce: '#1E3A8A',
  cellTrail: '#2563EB',
  cellGoal: '#F59E0B',
  cellStart: '#16A34A',
  timerWarning: '#FBBF24',
  timerCritical: '#FB7185',
  winFlash: '#7DD3FC',
  hintBg: '#0F172A',
  hintBorder: '#334155',
  hintText: '#CBD5E1',
  progressTrack: '#1E2A45',
  progressFill: '#2563EB',
} as const;

export const gameStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    alignItems: 'center',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  subtitle: {
    marginTop: 6,
    color: colors.textSecondary,
    fontSize: 16,
  },
  hudContainer: {
    marginTop: 10,
    width: '100%',
  },
  hudRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hudText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  hudTextCompact: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.15,
    flexShrink: 1,
  },
  hudRowCompact: {
    gap: 6,
  },
  hudTimeWarning: {
    color: colors.timerWarning,
  },
  hudTimeCritical: {
    color: colors.timerCritical,
  },
  progressTrack: {
    marginTop: 8,
    width: '100%',
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.progressTrack,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: colors.progressFill,
  },
  boardWrapper: {
    marginTop: 14,
    marginBottom: 16,
    width: '100%',
    alignItems: 'center',
    position: 'relative',
    flexGrow: 1,
    flexShrink: 1,
    justifyContent: 'center',
  },
  boardSlot: {
    width: '100%',
    maxWidth: 360,
    aspectRatio: 1,
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
  },
  board: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
    position: 'relative',
    overflow: 'hidden',
  },
  winFlashOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.winFlash,
  },
  boardRow: {
    flex: 1,
    flexDirection: 'row',
  },
  cell: {
    flex: 1,
    margin: 2,
    borderRadius: 8,
    backgroundColor: colors.cellEmpty,
    borderWidth: 1,
    borderColor: colors.cellEmptyBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellWall: {
    backgroundColor: colors.cellWall,
    borderColor: colors.cellWall,
  },
  cellIce: {
    backgroundColor: colors.cellIce,
    borderColor: colors.accent,
  },
  iceMarker: {
    color: '#93C5FD',
    fontSize: 10,
    fontWeight: '800',
    opacity: 0.85,
  },
  cellPainted: {
    backgroundColor: colors.cellTrail,
    borderColor: colors.cellTrail,
  },
  cellGoal: {
    backgroundColor: colors.cellGoal,
    borderColor: colors.cellGoal,
  },
  cellPlayer: {
    backgroundColor: colors.cellStart,
    borderColor: colors.cellStart,
  },
  playerEmoji: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    borderRadius: 6,
    overflow: 'hidden',
  },
  goalMarkerSlot: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalMarker: {
    width: '74%',
    height: '74%',
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalMarkerRing: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#FEF3C7',
  },
  goalMarkerCore: {
    width: '58%',
    height: '58%',
    borderRadius: 999,
    backgroundColor: '#FDE68A',
  },
  goalMarkerDot: {
    position: 'absolute',
    width: '28%',
    height: '28%',
    borderRadius: 999,
    backgroundColor: '#B45309',
  },
  levelTransitionOverlay: {
    ...StyleSheet.absoluteFillObject,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(11, 18, 32, 0.82)',
    zIndex: 20,
  },
  levelTransitionBadge: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  levelTransitionText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  dpad: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  dpadSpacer: {
    width: 40,
  },
  dpadButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: colors.buttonBg,
    borderWidth: 1,
    borderColor: colors.buttonBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpadArrow: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 20,
  },
  controlsSplit: {
    marginTop: 16,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    flexShrink: 0,
  },
  actionColumn: {
    flexShrink: 0,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  actionButton: {
    alignSelf: 'flex-start',
    minWidth: 142,
    maxWidth: 172,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.buttonBg,
    borderWidth: 1,
    borderColor: colors.buttonBorder,
    alignItems: 'center',
    marginBottom: 8,
  },
  actionButtonLast: {
    marginBottom: 0,
  },
  dpadColumn: {
    width: 128,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlsRow: {
    marginTop: 24,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  controlsButtonSize: {
    minWidth: 105,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  controlsButton: {
    marginHorizontal: 6,
  },
  resetButtonWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  resetHintBubble: {
    position: 'absolute',
    bottom: '100%',
    marginBottom: 6,
    alignSelf: 'center',
    backgroundColor: colors.hintBg,
    borderColor: colors.hintBorder,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 8,
    zIndex: 10,
  },
  resetHintText: {
    color: colors.hintText,
    fontSize: 11,
    fontWeight: '600',
  },
  button: {
    minWidth: 120,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.buttonBg,
    borderWidth: 1,
    borderColor: colors.buttonBorder,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonPressed: {
    transform: [{ scale: 0.99 }],
    backgroundColor: colors.buttonPressed,
  },
  buttonText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  buttonPrimary: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  buttonPrimaryText: {
    color: colors.accentText,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(11, 18, 32, 0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
    alignItems: 'center',
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  modalSubtitle: {
    marginTop: 8,
    color: colors.textSecondary,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  modalStatsRow: {
    marginTop: 16,
    marginBottom: 8,
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  modalStat: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  modalRoundBadge: {
    marginTop: 10,
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  modalCycleHint: {
    marginTop: 8,
    color: colors.textSecondary,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  modalPrimaryButton: {
    marginTop: 12,
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderColor: colors.accent,
    alignItems: 'center',
  },
  modalPrimaryButtonText: {
    color: colors.accentText,
    fontSize: 15,
    fontWeight: '800',
  },
  modalSecondaryButton: {
    marginTop: 10,
    width: '100%',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.buttonBg,
    borderWidth: 1,
    borderColor: colors.buttonBorder,
    alignItems: 'center',
  },
  modalSecondaryButtonText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  modalTertiaryButton: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  modalTertiaryButtonText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
});

export const introStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  introHeader: {
    paddingHorizontal: 16,
    alignItems: 'center',
    paddingBottom: 8,
  },
  roundLabel: {
    marginTop: 4,
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  introScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  title: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  subtitle: {
    marginTop: 6,
    color: colors.textSecondary,
    fontSize: 16,
  },
  introCard: {
    marginTop: 20,
    width: '100%',
    maxWidth: 420,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  introText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  introSectionTitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 10,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 10,
  },
  legendSwatch: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  legendLabel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  settingsRow: {
    marginTop: 12,
    width: '100%',
    maxWidth: 420,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  settingsLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  settingsToggle: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 56,
    alignItems: 'center',
  },
  settingsToggleOn: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  settingsToggleOff: {
    backgroundColor: 'transparent',
    borderColor: colors.buttonBorder,
  },
  settingsToggleText: {
    color: colors.textPrimary,
    fontWeight: '800',
    fontSize: 13,
  },
  settingsToggleTextOn: {
    color: colors.accentText,
  },
  primaryButton: {
    marginTop: 16,
    width: '100%',
    maxWidth: 420,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderColor: colors.accent,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: colors.accentText,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  resumePrimaryButtonText: {
    fontSize: 13,
  },
  introSecondaryButton: {
    marginTop: 10,
    width: '100%',
    maxWidth: 420,
  },
  button: {
    minWidth: 120,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.buttonBg,
    borderWidth: 1,
    borderColor: colors.buttonBorder,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonPressed: {
    transform: [{ scale: 0.99 }],
    backgroundColor: colors.buttonPressed,
  },
  buttonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  langToggleWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
  },
  langChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 56,
    alignItems: 'center',
  },
  langChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  langChipInactive: {
    backgroundColor: 'transparent',
    borderColor: colors.buttonBorder,
  },
  langChipText: {
    color: colors.textPrimary,
    fontWeight: '800',
  },
  langChipTextActive: {
    color: colors.accentText,
  },
});
